## Packages

In [2]:
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [3]:
from IPython.display import display, Latex

In [4]:
import warnings
warnings.filterwarnings("ignore")

## Collecting Data

### kaggle.com

In [87]:
import os
from dotenv import load_dotenv

In [88]:
load_dotenv()
os.environ["KAGGLE_USERNAME"] = os.environ.get("KAGGLE_USERNAME")
os.environ['KAGGLE_KEY'] = os.environ.get("KAGGEL_API_TOKEN")

In [89]:
import kaggle
kaggle.api.authenticate()

### github.com

In [90]:
gdp = pd.read_csv('https://raw.githubusercontent.com/datasets/gdp/refs/heads/main/data/gdp.csv')
gdpUSA = gdp[gdp['Country Code']=='USA']
gdpUSA.head(2)

,Country Name,Country Code,Year,Value
13340,United States,USA,1960,5.419886e+11
13341,United States,USA,1961,5.619403e+11


### `yf`

In [91]:
eurusd = yf.Ticker("EURUSD=X").history(start="2024-01-01", end="2024-02-01", interval="1d")
gbpusd = yf.Ticker("GBPUSD=X").history(start="2024-01-01", end="2024-02-01", interval="1d")
# eurusd.to_csv('../00-data/eurusd.csv')
# gbpusd.to_csv('../00-data/gbpusd.csv')

In [92]:
# apple = yf.Ticker("AAPL").history(start="2025-06-01", end="2025-06-20", interval="1d")
apple = yf.Ticker("AAPL").history(start="1996-06-01", end="1996-06-16", interval="1d")
microsoft = yf.Ticker("MSFT").history(start="1996-06-01", end="1996-06-16", interval="1d")

google = yf.Ticker("GOOG").history(start="2021-06-01", end="2025-06-16", interval="1d")
amazon = yf.Ticker("AMZN").history(start="2025-06-01", end="2025-06-16", interval="1d")

byd = yf.Ticker("BYDDY").history(start="2025-09-01", end="2025-09-10", interval="1d")
tesla = yf.Ticker("TSLA").history(start="2025-09-01", end="2025-09-10", interval="1d")

In [93]:
coke = yf.Ticker("COKE").history(start="2025-09-01", end="2025-09-10", interval="1d")
coke.Open.round()

Date
2025-09-02 00:00:00-04:00    116.0
2025-09-03 00:00:00-04:00    116.0
2025-09-04 00:00:00-04:00    117.0
2025-09-05 00:00:00-04:00    119.0
2025-09-08 00:00:00-04:00    120.0
2025-09-09 00:00:00-04:00    122.0
Name: Open, dtype: float64

In [94]:
pepsi = yf.Ticker("PEP").history(start="2025-09-01", end="2025-09-10", interval="1d")
pepsi.Open.round()

Date
2025-09-02 00:00:00-04:00    154.0
2025-09-03 00:00:00-04:00    147.0
2025-09-04 00:00:00-04:00    146.0
2025-09-05 00:00:00-04:00    145.0
2025-09-08 00:00:00-04:00    144.0
2025-09-09 00:00:00-04:00    140.0
Name: Open, dtype: float64

In [95]:
pepper = yf.Ticker("KDP").history(start="2025-09-01", end="2025-09-10", interval="1d")
pepper.Open.round()

Date
2025-09-02 00:00:00-04:00    29.0
2025-09-03 00:00:00-04:00    28.0
2025-09-04 00:00:00-04:00    29.0
2025-09-05 00:00:00-04:00    29.0
2025-09-08 00:00:00-04:00    28.0
2025-09-09 00:00:00-04:00    27.0
Name: Open, dtype: float64

In [96]:
monster = yf.Ticker("MNST").history(start="2025-09-01", end="2025-09-10", interval="1d")
monster.Open.round()

Date
2025-09-02 00:00:00-04:00    62.0
2025-09-03 00:00:00-04:00    62.0
2025-09-04 00:00:00-04:00    64.0
2025-09-05 00:00:00-04:00    64.0
2025-09-08 00:00:00-04:00    62.0
2025-09-09 00:00:00-04:00    63.0
Name: Open, dtype: float64

## Ordinary Least Squares OLS

Linear regression is a fundamental statistical technique used to model the relationship between a dependent variable ($Y$ also known as the response or target variable) and one or more independent variables (also known as predictors or features $X$). 

The **Gauss-Markov theorem** states 
that **Ordinary Least Squares (OLS)** estimators 
are the **best linear unbiased estimators (BLUE)** 
in a linear regression model, 
meaning they have the minimum variance among all linear unbiased estimators.

### Hypothesis Testing

In [97]:
from scipy.stats import t, f

In statistics, a test of significance is a method of reaching a conclusion to either reject or accept certain claims based on the data. 

In the case of regression analysis, it is used to determine whether an independent variable is significant in explaining the variance of the dependent variable.

$$y = \beta x + \alpha$$

* The **null hypothesis H0** would be: $\beta=0$ i.e predictor $x$ is not able to explain the variance of the independent variable $y$.
* Alternative hypothesis **H1** would be: $\beta\neq 0$ i.e $x$ is significant in predicting the value of $y$.

#### F-statistics

Since here we have only one predictor a **T-test** should be enough. 
However, in reality, our model is going to include a number of independent variables. 
This is where **F-statistic** comes into play.

An insignificant **F-test** implies that the predictors have no linear relationship with the target variable.

**F-statistics** is based on the ratio of two variances: the explained variance ($(\hat{y}-\bar{y})$ due to the model) and the unexplained variance ($(y-\bar{y})$ residuals). 
In other words, **F-statistics** compares the explained variance (due to the model) and the unexplained variance (residuals). 
By comparing these variances, **F-statistics** helps us determine whether the regression model significantly explains the variation in the dependent variable or if the variation can be attributed to random chance.

The **F-statistic** follows an **F-distribution**, and its value helps to determine the probability (**p-value**) of observing such a statistic if **the null hypothesis** is true 
(i.e., no relationship between the dependent and independent variables). 
If the **p-value** is smaller than a predetermined significance level (e.g., 0.05), the null hypothesis is rejected, 
and we conclude that the regression model is statistically significant.

* `dfn`: Degrees of freedom for the numerator (often associated with the variance of the group means in ANOVA).
* `dfd`: Degrees of freedom for the denominator (often associated with the variance within groups in ANOVA).

* If the **p-value** associated with the **F-statistic** is ≥ 0.05: Then there is no relationship between ANY of the independent variables and Y
* If the **p-value** associated with the **F-statistic** < 0.05: Then, AT LEAST 1 independent variable is related to Y

In **F-test** hypothesis testing for linear regression, the **F-statistic** is primarily assessed by comparing it against a critical value from the **F-distribution**, based on the model’s and error’s degrees of freedom and a chosen significance level, like 0.05. 

Additionally, the **p-value** associated with the **F-statistic**, typically calculated using statistical software, plays a key role; if it’s below the significance threshold, it indicates the model’s statistical significance, leading to the rejection of the null hypothesis.

### 2D Playground

#### Intro

Classical normal linear regression assumptions (LINE):

L (**Linearity**). A linear relation exists between $Y_i$ and $X_i$. This means the mean value for $Y$ at each level of $X$ falls on the regression line. 
$$Y = \beta X + \alpha + \varepsilon$$
I (**Independence**). - The error terms $\varepsilon$ are independent of the values of the independent variable $X$. That is, there's no connection between how far any two points lie from the regression line. \
N (**Normality**). For any value $X$, the error term $\varepsilon$ has a normal distribution. \
E (**Homoscedasticity**). The variance of the error term ($\varepsilon$), denoted $\sigma^2$, is the same for all $X$. That is, the spread in the $Y$'s for each level of $X$ is the same.

When $\sigma^2$ is small, an observed point $(X_i,  Y_i)$ will almost always fall quite close to the true regression line, 
whereas observations may deviate considerably from their expected values (corresponding to points far from the line) when $\sigma^2$ is large.

Thus, this variance can be used to tell us how good the linear fit is. 

In [98]:
# sns.scatterplot(data=gdpUSA, x='Year', y='Value')
# plt.show()

$$\beta = \frac{n\sum X_i Y_i -\big(\sum X_i\big)\big(\sum Y_i\big)}{n\sum X_i^2 - \big(\sum X_i\big)^2} = \frac{\text{COV}(X, Y)}{\text{VAR}(X)}$$

$$\alpha = \frac{1}{n}\sum Y_i + \frac{1}{n}\sum X_i \beta = \bar{Y}-\bar{X}\beta$$

#### 1

In [99]:
# x = np.array([2, 4, 6, 7, 9])
# y = np.array([5, 10, 10, 15, 20])
x = np.array([5, 11, 15, 17, 20, 22, 25, 27, 30, 35]) 
y = np.array([70, 65, 55, 60, 50, 35, 40, 30, 25, 32])

In [100]:
display(Latex(f"$\sum xy = {np.inner(x, y)}$"))
display(Latex(f"$\sum x = {np.sum(x)}$"))
display(Latex(f"$\sum y = {np.sum(y)}$"))
display(Latex(f"$\sum x^2 = {sum([num ** 2 for num in x])}$"))
display(Latex(f"$\sum y^2 = {sum([num ** 2 for num in y])}$"))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [101]:
beta = (len(x)*np.inner(x, y)-np.sum(x)*np.sum(y))/(len(x)*sum([num ** 2 for num in x]) - np.sum(x)*np.sum(x))
beta

np.float64(-1.6304023845007451)

In [102]:
alpha = (np.sum(y) - beta * np.sum(x))/len(x)
alpha

np.float64(79.94932935916543)

In [103]:
x * beta + alpha

array([71.79731744, 62.01490313, 55.49329359, 52.23248882, 47.34128167,
       44.0804769 , 39.18926975, 35.92846498, 31.03725782, 22.8852459 ])

In [104]:
1 - sum([num ** 2 for num in x * beta + alpha - y])/sum([num ** 2 for num in y - np.mean(y)])

np.float64(0.8606888179979808)

#### 2

In [105]:
# x = np.array([1, 3, 5, 5, 6])
# y = np.array([2, 1.5, 1.6, 1.4, 1])
x = np.array([2, 4, 5, 6, 8])
y = np.array([135, 128, 120, 118, 110])

In [106]:
display(Latex(f"$\sum xy = {np.inner(x, y)}$"))
display(Latex(f"$\sum x = {np.sum(x)}$"))
display(Latex(f"$\sum y = {np.sum(y)}$"))
display(Latex(f"$\sum x^2 = {sum([num ** 2 for num in x])}$"))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [107]:
beta = (len(x)*np.inner(x, y)-np.sum(x)*np.sum(y))/(len(x)*sum([num ** 2 for num in x]) - np.sum(x)*np.sum(x))
beta

np.float64(-4.25)

In [108]:
alpha = (np.sum(y) - beta * np.sum(x))/len(x)
alpha

np.float64(143.45)

**несмещенной оценкой дисперсии ошибок**

In [109]:
e = y - alpha - beta * x # unbiased estimate of error
sigma2 = sum([num ** 2 for num in e])/(len(x)-2)
sigma2

np.float64(2.516666666666667)

**Дисперсия оценки** $\beta$

In [110]:
sigma_b = np.sqrt( sigma2/sum( [ num**2 for num in (x-x.mean()) ] ) )
sigma_b

np.float64(0.3547299442298794)

In [111]:
2.516/20

0.1258

**Дисперсия оценки** $\alpha$

In [112]:
sigma_a = np.sqrt( sigma2 * sum ([num**2 for num in x]) / (len(x) * sum([num**2 for num in x-x.mean()])) )
sigma_a**2

np.float64(3.6491666666666673)

In [113]:
print(beta/sigma_b, alpha/sigma_a)

-11.980945136240958 75.09373452903537


#### 3

In [114]:
x = np.array([1, 3, 4, 6, 8])
y = np.array([8, 12, 15, 20, 24])

In [115]:
display(Latex(f"$\sum xy = {np.inner(x, y)}$"))
display(Latex(f"$\sum x = {np.sum(x)}$"))
display(Latex(f"$\sum y = {np.sum(y)}$"))
display(Latex(f"$\sum x^2 = {sum([num ** 2 for num in x])}$"))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [116]:
beta = (len(x)*np.inner(x, y)-np.sum(x)*np.sum(y))/(len(x)*sum([num ** 2 for num in x]) - np.sum(x)*np.sum(x))
beta

np.float64(2.3424657534246576)

In [117]:
alpha = (np.sum(y) - beta * np.sum(x))/len(x)
alpha

np.float64(5.493150684931507)

In [118]:
e = y - alpha - beta * x # unbiased estimate of error
sigma2 = sum([num ** 2 for num in e])/(len(x)-2)
sigma2

np.float64(0.19178082191780824)

In [119]:
sigma_b = np.sqrt( sigma2/sum( [ num**2 for num in (x-x.mean()) ] ) )
sigma_b**2

np.float64(0.006567836367048228)

In [120]:
sigma_a = np.sqrt( sigma2 * sum ([num**2 for num in x]) / (len(x) * sum([num**2 for num in x-x.mean()])) )
sigma_a


np.float64(0.4068285590388356)

In [121]:
print(beta/sigma_b, alpha/sigma_a)

28.904275511715266 13.50237234551455


In [122]:
x = np.array([5, 6, 7, 8, 9])
y = np.array([200, 140, 110, 85, 70])

In [123]:
lnx = np.log(x)
lny = np.log(y)

In [124]:
display(Latex(f"$\sum lnxlny = {np.inner(lnx, lny)}$"))
display(Latex(f"$\sum lnx = {np.sum(lnx)}$"))
display(Latex(f"$\sum lny = {np.sum(lny)}$"))
display(Latex(f"$\sum lnx^2 = {sum([num ** 2 for num in lnx])}$"))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [125]:
beta = (len(lnx)*np.inner(lnx, lny)-np.sum(lnx)*np.sum(lny))/(len(lnx)*sum([num ** 2 for num in lnx]) - np.sum(lnx)*np.sum(lnx))
beta

np.float64(-1.7782433547169036)

In [126]:
alpha = (np.sum(lny) - beta * np.sum(lnx))/len(lnx)
alpha

np.float64(8.148999638685542)

In [127]:
e = lny - alpha - beta * lnx # unbiased estimate of error
sigma2 = sum([num ** 2 for num in e])/(len(lnx)-2)
sigma2

np.float64(0.00027776375504360017)

#### 4

##### 2D

In [128]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 16, 35, 55, 86])

In [129]:
display(Latex(f"$\sum xy = {np.inner(x, y)}$"))
display(Latex(f"$\sum x = {np.sum(x)}$"))
display(Latex(f"$\sum y = {np.sum(y)}$"))
display(Latex(f"$\sum x^2 = {sum([num ** 2 for num in x])}$"))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [130]:
beta = (len(x)*np.inner(x, y)-np.sum(x)*np.sum(y))/(len(x)*sum([num ** 2 for num in x]) - np.sum(x)*np.sum(x))
beta

np.float64(19.9)

In [131]:
alpha = (np.sum(y) - beta * np.sum(x))/len(x)
alpha

np.float64(-20.1)

In [132]:
e = y - alpha - beta * x # unbiased estimate of error
sigma2 = sum([num ** 2 for num in e])/(len(x)-2)
sigma2

np.float64(45.69999999999996)

In [133]:
sigma_b = np.sqrt( sigma2/sum( [ num**2 for num in (x-x.mean()) ] ) )
print(sigma_b**2, sigma_b)

4.569999999999997 2.1377558326431942


In [134]:
sigma_a = np.sqrt( sigma2 * sum ([num**2 for num in x]) / (len(x) * sum([num**2 for num in x-x.mean()])) )
print(sigma_a**2, sigma_a)

50.26999999999995 7.090133990271267


In [135]:
print(beta/sigma_b, alpha/sigma_a)

9.308827367527263 -2.8349252676437757


In [136]:
TSS = sum([num**2 for num in y-y.mean()])
TSS

np.float64(4097.200000000001)

In [137]:
R=1-sigma2*(len(x)-2)/TSS
R

np.float64(0.9665381235966026)

In [138]:
F=(len(x)-2)*R/(1-R)
F

np.float64(86.6542669584247)

In [139]:
# 2. Add a constant to the independent variable for the intercept
# This creates the design matrix for statsmodels
X_with_intercept = sm.add_constant(x)
# 3. Create and fit the OLS (Ordinary Least Squares) model
model = sm.OLS(y, X_with_intercept)
results = model.fit()
# 4. Print the detailed summary
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.967
Model:                            OLS   Adj. R-squared:                  0.955
Method:                 Least Squares   F-statistic:                     86.65
Date:                Wed, 25 Feb 2026   Prob (F-statistic):            0.00262
Time:                        12:41:04   Log-Likelihood:                -15.373
No. Observations:                   5   AIC:                             34.75
Df Residuals:                       3   BIC:                             33.96
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        -20.1000      7.090     -2.835      0.0

##### 3D

In [140]:
x1 = np.array([40,50,40,30,30])
x2 = np.array([60,40,40,20,90])
y = np.array([3,6,5,3,1])
p=2

In [141]:
I = np.array([1, 1, 1, 1, 1])

In [142]:
x = np.array([I, x1, x2]) @ np.array([I, x1, x2]).T
x

array([[    5,   190,   250],
       [  190,  7500,  9300],
       [  250,  9300, 15300]])

In [143]:
np.linalg.inv(x) 

array([[ 7.59677419e+00, -1.56451613e-01, -2.90322581e-02],
       [-1.56451613e-01,  3.76344086e-03,  2.68817204e-04],
       [-2.90322581e-02,  2.68817204e-04,  3.76344086e-04]])

In [144]:
np.array([I, x1, x2]) @ y

array([ 18, 740, 770])

In [145]:
np.array([I, x1, x2]) @ y

array([ 18, 740, 770])

In [146]:
beta = np.linalg.inv(x) @ np.array([I, x1, x2]) @ y
print( beta)

[-1.38709677  0.17580645 -0.03387097]


In [147]:
e = y - beta @ np.array([I, x1, x2]) # unbiased estimate of error
sigma2 = sum([num ** 2 for num in e])/(len(y)-p-1)
sigma = np.sqrt(sigma2)

display(Latex(f"$\sum  e^2 = {sum([num ** 2 for num in e])}$"))
display(Latex(r"$\sigma^2 = \frac{1}{n-p-1}\sum e^2" + f" =  {sigma2}$"))
display(Latex(f"$\sigma = {sigma}$"))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [148]:
sigma_0 = np.sqrt( sigma2 * np.linalg.inv(x)[0, 0])
sigma_1 = np.sqrt( sigma2 * np.linalg.inv(x)[1, 1])
sigma_2 = np.sqrt( sigma2 * np.linalg.inv(x)[2, 2])
# sigma2 = 7.06
display(Latex(f"$\sigma^2_0 " + f" =  {sigma_0**2}$"))
display(Latex(f"$\sigma_0 =  {sigma_0}$"))
display(Latex(f"$\sigma^2_1 = " + r"\frac{\sigma^2}{\sum (x_1-\bar{x_1})^2}" + f" =  {sigma_1**2}$"))
display(Latex(f"$\sigma_1 =  {sigma_1}$"))
display(Latex(f"$\sigma^2_2 = " + r"\frac{\sigma^2}{\sum (x_2-\bar{x_2})^2}" + f" =  {sigma_2**2}$"))
display(Latex(f"$\sigma_2 =  {sigma_2}$"))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [149]:
# Convert to pandas DataFrame for easier handling, especially with the formula API
df = pd.DataFrame(np.array([x1, x2]).T, columns=['x1', 'x2'])
df['y'] = y

In [150]:
# Method 2: Using the formula API (often more convenient)
# Requires 'statsmodels.formula.api'
model_formula = smf.ols("y ~ x1 + x2", data=df)
results_formula = model_formula.fit()
# 4. Print the summary of the regression results
print("Results from formula OLS:")
print(results_formula.summary())

Results from formula OLS:
                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.937
Model:                            OLS   Adj. R-squared:                  0.875
Method:                 Least Squares   F-statistic:                     14.97
Date:                Wed, 25 Feb 2026   Prob (F-statistic):             0.0626
Time:                        12:41:04   Log-Likelihood:                -2.9471
No. Observations:                   5   AIC:                             11.89
Df Residuals:                       2   BIC:                             10.72
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -1.3871     

#### 5

##### 2D 

In [151]:
x = np.array([130, 145, 150, 160, 175])
y = np.array([128, 115, 112, 104, 92])

In [152]:
x*x

array([16900, 21025, 22500, 25600, 30625])

In [153]:
display(Latex(f"$\sum xy = {np.inner(x, y)}$"))
display(Latex(f"$\sum x = {np.sum(x)}$"))
display(Latex(f"$\sum y = {np.sum(y)}$"))
display(Latex(f"$\sum x^2 = {sum([num ** 2 for num in x])}$"))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [154]:
beta = (len(x)*np.inner(x, y)-np.sum(x)*np.sum(y))/(len(x)*sum([num ** 2 for num in x]) - np.sum(x)*np.sum(x))
beta

np.float64(-0.7938053097345132)

In [155]:
alpha = (np.sum(y) - beta * np.sum(x))/len(x)
alpha

np.float64(230.85840707964599)

**несмещенной оценкой дисперсии ошибок**

In [156]:
e = y - alpha - beta * x # unbiased estimate of error
sigma2 = sum([num ** 2 for num in e])/(len(x)-2)
sigma2

np.float64(0.25221238938053375)

In [157]:
sigma2*3

np.float64(0.7566371681416013)

In [158]:
sigma_b = np.sqrt( sigma2/sum( [ num**2 for num in (x-x.mean()) ] ) )
print(sigma_b**2, sigma_b)

0.00022319680476153426 0.014939772580649756


In [159]:
x = np.array([15, 20, 25, 30, 35])
y = np.array([80, 110, 130, 145, 150])

In [160]:
display(Latex(f"$\sum xy = {np.inner(x, y)}$"))
display(Latex(f"$\sum x = {np.sum(x)}$"))
display(Latex(f"$\sum y = {np.sum(y)}$"))
display(Latex(f"$\sum x^2 = {sum([num ** 2 for num in x])}$"))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [161]:
beta = (len(x)*np.inner(x, y)-np.sum(x)*np.sum(y))/(len(x)*sum([num ** 2 for num in x]) - np.sum(x)*np.sum(x))
beta

np.float64(3.5)

In [162]:
alpha = (np.sum(y) - beta * np.sum(x))/len(x)
alpha

np.float64(35.5)

**несмещенная оценка дисперсии ошибок**

In [163]:
e = y - alpha - beta * x # unbiased estimate of error
sigma2 = sum([num ** 2 for num in e])/(len(x)-2)
sigma2

np.float64(72.5)

**Дисперсия оценки** $\beta$

In [164]:
sigma_b = np.sqrt( sigma2/sum( [ num**2 for num in (x-x.mean()) ] ) )
print(sigma_b**2, sigma_b)

0.29 0.5385164807134504


**Дисперсия оценки** $\alpha$

In [165]:
sigma_a = np.sqrt( sigma2 * sum ([num**2 for num in x]) / (len(x) * sum([num**2 for num in x-x.mean()])) )
print(sigma_a**2, sigma_a)

195.74999999999997 13.991068579633222


In [166]:
print(beta/sigma_b, alpha/sigma_a)

6.499336836196815 2.5373329991161144


In [167]:
ESS = sigma2*(len(x)-2)
TSS = sum( [num**2 for num in y - y.mean()])
RSS = sum( [num**2 for num in alpha + beta * x - y.mean()])

In [168]:
TSS - ESS - RSS

np.float64(0.0)

In [169]:
TSS

np.float64(3280.0)

**коэффициент детерминации**

In [170]:
R2 = 1-ESS/TSS
R2

np.float64(0.9336890243902439)

**$F$-статистика**

In [171]:
F = R2*(len(x)-2)/(1-R2)
F

np.float64(42.24137931034485)

Применение линейной регрессии

In [172]:
# 2. Add a constant to the independent variable for the intercept
# This creates the design matrix for statsmodels
X_with_intercept = sm.add_constant(x)
# 3. Create and fit the OLS (Ordinary Least Squares) model
model = sm.OLS(y, X_with_intercept)
results = model.fit()
# 4. Print the detailed summary
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.934
Model:                            OLS   Adj. R-squared:                  0.912
Method:                 Least Squares   F-statistic:                     42.24
Date:                Wed, 25 Feb 2026   Prob (F-statistic):            0.00740
Time:                        12:41:06   Log-Likelihood:                -16.527
No. Observations:                   5   AIC:                             37.05
Df Residuals:                       3   BIC:                             36.27
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         35.5000     13.991      2.537      0.0

In [173]:
3.5-3.182*0.539

1.784902

##### 3D

In [174]:
x1 = np.array([3.5, 3.2, 3.0, 2.8, 2.5])
x2 = np.array([3.6, 3.5, 3.4, 3.4, 3.5])
y = np.array([0.8, 1, 1.2, 1.1, 1.0])
p=2

In [175]:
x = np.array([x1, x2]) @ np.array([x1, x2]).T
x

array([[45.58, 52.27],
       [52.27, 60.58]])

In [176]:
np.linalg.inv(x) 

array([[ 2.08296801, -1.79723898],
       [-1.79723898,  1.56721165]])

In [177]:
np.array([x1, x2]) @ y

array([15.18, 17.7 ])

In [178]:
beta = np.linalg.inv(x) @ np.array([x1, x2]) @ y
print( beta)

[-0.19167569  0.45755841]


In [179]:
15.18*2.08-1.8*17.7

-0.28559999999999874

#### 6

##### 2D

In [223]:
x = np.array([25, 30, 38, 45, 52])
y = np.array([4.8, 4.5, 4.1, 3.7, 3.3])

In [224]:
display(Latex(f"$\sum xy = {np.inner(x, y)}$"))
display(Latex(f"$\sum x = {np.sum(x)}$"))
display(Latex(f"$\sum y = {np.sum(y)}$"))
display(Latex(f"$\sum x^2 = {sum([num ** 2 for num in x])}$"))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [225]:
beta = (len(x)*np.inner(x, y)-np.sum(x)*np.sum(y))/(len(x)*sum([num ** 2 for num in x]) - np.sum(x)*np.sum(x))
beta

np.float64(-0.055020920502092244)

In [226]:
alpha = (np.sum(y) - beta * np.sum(x))/len(x)
alpha

np.float64(6.170794979079505)

**несмещенная оценка дисперсии ошибок**

In [184]:
# beta=-0.055
# alpha=6.17

In [228]:
e

array([ 0.00472803, -0.02016736,  0.02      ,  0.00514644, -0.00970711])

In [229]:
e = y - alpha - beta * x # unbiased estimate of error
sigma2 = sum([num ** 2 for num in e])/(len(x)-2)
sigma2

np.float64(0.00031659693165969155)

**Дисперсия оценки** $\beta$

In [230]:
sum( [ num**2 for num in (x-x.mean()) ])

np.float64(478.0)

In [186]:
sigma_b = np.sqrt( sigma2/sum( [ num**2 for num in (x-x.mean()) ] ) )
print(sigma_b**2, sigma_b)

6.623366771123254e-07 0.0008138406951684865


**Дисперсия оценки** $\alpha$

In [187]:
sigma_a = np.sqrt( sigma2 * sum ([num**2 for num in x]) / (len(x) * sum([num**2 for num in x-x.mean()])) )
print(sigma_a**2, sigma_a)

0.0010197335480821362 0.03193326710629741


In [188]:
print(beta/sigma_b, alpha/sigma_a)

-67.60649943991983 193.24032704009142


In [231]:
ESS = sigma2*(len(x)-2)
TSS = sum( [num**2 for num in y - y.mean()])
RSS = sum( [num**2 for num in alpha + beta * x - y.mean()])
TSS - ESS - RSS

np.float64(-1.021405182655144e-14)

In [232]:
TSS

np.float64(1.448)

**коэффициент детерминации**

In [191]:
R2 = 1-ESS/TSS
R2

np.float64(0.9993440671305394)

**$F$-статистика**

In [233]:
F = R2*(len(x)-2)/(1-R2)
F

np.float64(4570.638766520172)

In [193]:
# 2. Add a constant to the independent variable for the intercept
# This creates the design matrix for statsmodels
X_with_intercept = sm.add_constant(x)
# 3. Create and fit the OLS (Ordinary Least Squares) model
model = sm.OLS(y, X_with_intercept)
results = model.fit()
# 4. Print the detailed summary
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.999
Model:                            OLS   Adj. R-squared:                  0.999
Method:                 Least Squares   F-statistic:                     4571.
Date:                Wed, 25 Feb 2026   Prob (F-statistic):           7.13e-06
Time:                        12:41:07   Log-Likelihood:                 14.327
No. Observations:                   5   AIC:                            -24.65
Df Residuals:                       3   BIC:                            -25.44
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          6.1708      0.032    193.240      0.0

In [194]:
6.17-3.182*0.03

6.07454

##### 3D

In [195]:
x1 = np.array([3.5, 3.2, 3.0, 2.8, 2.5])
x2 = np.array([7.2, 7.4, 7.5, 7.4, 7.3])
y = np.array([-0.5, -0.3, 0.1, 0.5, 0.7])

I = np.array([1, 1, 1, 1, 1])
p=2

In [196]:
x = np.array([I, x1, x2]) @ np.array([I, x1, x2]).T
x

array([[  5.  ,  15.  ,  36.8 ],
       [ 15.  ,  45.58, 110.35],
       [ 36.8 , 110.35, 270.9 ]])

In [197]:
np.linalg.inv(x) 

array([[1232.82357194,  -18.94432393, -159.75415763],
       [ -18.94432393,    1.87997108,    1.8076645 ],
       [-159.75415763,    1.8076645 ,   20.96890817]])

In [198]:
np.array([I, x1, x2]) @ y

array([0.5 , 0.74, 3.74])

In [199]:
np.array([-18.94432, 1.8928, 1.80766]) @ np.array([I, x1, x2]) @ y

np.float64(-1.3108396000000009)

In [200]:
beta = np.linalg.inv(x) @ np.array([I, x1, x2]) @ y
print( beta)

[ 4.91243673 -1.32031815 -0.11569053]


In [201]:
beta = np.array([4.9167, -1.31, -0.114])

In [202]:
y-np.array([I, x1, x2]).T @ beta.T

array([-0.0109, -0.1811, -0.0317,  0.0949, -0.1095])

**несмещенной оценкой дисперсии ошибок**

In [203]:
e = y - beta @ np.array([I, x1, x2]) # unbiased estimate of error
sigma2 = sum([num ** 2 for num in e])/(len(y)-p-1)
sigma = np.sqrt(sigma2)

display(Latex(f"$\sum  e^2 = {sum([num ** 2 for num in e])}$"))
display(Latex(r"$\sigma^2 = \frac{1}{n-p-1}\sum e^2" + f" =  {sigma2}$"))
display(Latex(f"$\sigma = {sigma}$"))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [204]:
sigma_0 = np.sqrt( sigma2 * np.linalg.inv(x)[0, 0])
sigma_1 = np.sqrt( sigma2 * np.linalg.inv(x)[1, 1])
sigma_2 = np.sqrt( sigma2 * np.linalg.inv(x)[2, 2])
# sigma2 = 7.06
display(Latex(f"$\sigma^2_0 " + f" =  {sigma_0**2}$"))
display(Latex(f"$\sigma_0 =  {sigma_0}$"))
display(Latex(f"$\sigma^2_1 = " + r"\frac{\sigma^2}{\sum (x_1-\bar{x_1})^2}" + f" =  {sigma_1**2}$"))
display(Latex(f"$\sigma_1 =  {sigma_1}$"))
display(Latex(f"$\sigma^2_2 = " + r"\frac{\sigma^2}{\sum (x_2-\bar{x_2})^2}" + f" =  {sigma_2**2}$"))
display(Latex(f"$\sigma_2 =  {sigma_2}$"))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [205]:
# Convert to pandas DataFrame for easier handling, especially with the formula API
df = pd.DataFrame(np.array([x1, x2]).T, columns=['x1', 'x2'])
df['y'] = y

In [206]:
# Method 2: Using the formula API (often more convenient)
# Requires 'statsmodels.formula.api'
model_formula = smf.ols("y ~ x1 + x2", data=df)
results_formula = model_formula.fit()
# 4. Print the summary of the regression results
print("Results from formula OLS:")
print(results_formula.summary())

Results from formula OLS:
                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.958
Model:                            OLS   Adj. R-squared:                  0.916
Method:                 Least Squares   F-statistic:                     22.91
Date:                Wed, 25 Feb 2026   Prob (F-statistic):             0.0418
Time:                        12:41:07   Log-Likelihood:                 4.7664
No. Observations:                   5   AIC:                            -3.533
Df Residuals:                       2   BIC:                            -4.705
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      4.9124     

In [207]:
print( beta)

[ 4.9167 -1.31   -0.114 ]


#### Control Work 1

##### Variants

###### 2 курс

Әділқызы Шырайлым 

In [ ]:
# variant 01
x = np.array([2, -1, 4, 1, -2])
y = np.array([4, -2, 7, -2, -5])

Бектемір Лия Ерболқызы

In [ ]:
# variant 02
x = np.array([35, 50, 70, 85, 110])
y = np.array([70, 95, 145, 180, 230])

Бондарев Артем Николаевич 

In [ ]:
# variant 03
x = np.array([4, 8, 12, 15, 21])
x = np.array([2, 5, 7, 10, 12])

Кундебаев Көбейсін Нұрғалиұлы  

In [ ]:
# variant 04
x = np.array([10, 15, 20, 25, 30])
y = np.array([100, 85, 70, 40, 25])

Сайнов Дидар Сабыржанұлы

In [ ]:
# variant 05
x = np.array([2, 5, 8, 12, 15])
y = np.array([45, 60, 75, 85, 95])

Турганов Алмат Алтынбаевич  

In [ ]:
# variant 06
x = np.array([2, 4, 5, 7, 10])
y = np.array([70, 110, 120, 160, 210])

Юсубова Назлы Видадикызы 

In [ ]:
# variant 07
x = np.array([500, 1200, 1800, 2500, 3200])
y = np.array([18.0, 13.5, 9.0, 5.5, 1.0])

###### 1 Курс

Бурлибаев Батырхан Сакенович 

In [ ]:
# variant 08
x = np.array([500, 1200, 2500, 4000, 5500])
y = np.array([0.02, 0.05, 0.11, 0.18, 0.24])

Гончаров Никита Витальевич 

In [ ]:
# variant 09
x = np.array([150, 200, 250, 300, 350])
y = np.array([15, 22, 28, 35, 40])

Кан Владимир Игоревич  

In [ ]:
# variant 10
x = np.array([4, 6, 10, 14, 16])
y = np.array([72, 68, 62, 58, 55])

Лучихин Алексей Павлович  

In [ ]:
# variant 11
x = np.array([15, 25, 40, 55, 70])
y = np.array([35, 30, 22, 16, 10])

##### Checking

###### 1

Выписать оцененную модель.

In [209]:
from IPython.display import display, Latex

In [210]:
display(Latex(f"$\sum xy = {np.inner(x, y)}$"))
display(Latex(f"$\sum x = {np.sum(x)}$"))
display(Latex(f"$\sum y = {np.sum(y)}$"))
display(Latex(f"$\sum x^2 = {sum([num ** 2 for num in x])}$"))
display(Latex(f"$\sum y^2 = {sum([num ** 2 for num in y])}$"))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [211]:
beta = (len(x)*np.inner(x, y)-np.sum(x)*np.sum(y))/(len(x)*sum([num ** 2 for num in x]) - np.sum(x)*np.sum(x))
beta

np.float64(19.9)

In [212]:
# beta = 2.1724
alpha = (np.sum(y) - beta * np.sum(x))/len(x)
alpha

np.float64(-20.1)

###### 2

Найти стандартную ошибку модели и стандартные ошибки коэффициентов регрессии.

In [213]:
e = y - alpha - beta * x # unbiased estimate of error
sigma2 = sum([num ** 2 for num in e])/(len(x)-p-1)
sigma = np.sqrt(sum([num ** 2 for num in e])/(len(x)-p-1))

display(Latex(f"$\sum  e^2 = {sum([num ** 2 for num in e])}$"))
display(Latex(r"$\sigma^2 = \frac{1}{n-2}\sum e^2" + f" =  {sum([num ** 2 for num in e])/(len(x)-p-1)}$"))
display(Latex(f"$\sigma = {np.sqrt((sum([num ** 2 for num in e])/(len(x)-p-1)))}$"))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

**Дисперсия оценки** $\beta$

In [214]:
sigma_b = np.sqrt( sigma2.round(decimals=2)/sum( [ num**2 for num in (x-x.mean()) ] ) )
# sigma2 = 7.06

display(Latex(f"$\sigma^2_b = " + r"\frac{\sigma^2}{\sum (x-\bar{x})^2}" + f" =  {sigma2/sum( [num**2 for num in (x-x.mean())])}$"))
display(Latex(f"$\sigma_b =  {np.sqrt(sigma2/sum( [num**2 for num in (x-x.mean())]))}$"))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

**Дисперсия оценки** $\alpha$

In [215]:
sigma_a = np.sqrt( sigma2 * sum ([num**2 for num in x]) / (len(x) * sum([num**2 for num in x-x.mean()])) )

print(f"\u03C3^2_a = \u03C3^2\u03A3 x^2/ n\u03A3 (x-x_avg)^2=  {sigma_a**2}")
print(f"\u03C3_a =  {sigma_a}")

σ^2_a = σ^2Σ x^2/ nΣ (x-x_avg)^2=  50.26999999999995
σ_a =  7.090133990271267


In [216]:
print(f"\u03C3_b = {sigma_b},    \u03C3_a = {sigma_a}")

σ_b = 2.137755832643195,    σ_a = 7.090133990271267


###### 3

Построить 95%-е доверительные интервалы для коэффициентов регрессии.

In [ ]:
t.ppf(0.025, len(x)-2)

In [ ]:
palpha = 0.025
print(f"{beta + t.ppf(palpha, len(x)-2)*sigma_b}, {beta - t.ppf(palpha, len(x)-2)*sigma_b}")

In [ ]:
palpha = 0.025
print(f"{alpha + t.ppf(palpha, len(x)-2)*sigma_a}, {alpha - t.ppf(palpha, len(x)-2)*sigma_a}")

###### 4

Найти коэффициент детерминации модели и сделать соответствующий вывод о качестве аппроксимации данных.

In [ ]:
ESS = sigma2*(len(x)-2)
TSS = sum( [num**2 for num in y - y.mean()])
RSS = sum( [num**2 for num in alpha + beta * x - y.mean()])
TSS - ESS - RSS

TSS = 4097.200000000001
RSS = 3960.100000000001


**коэффициент детерминации**

In [ ]:
R2 = 1-ESS/TSS
R2

###### 5

Проверить на 5%-ю значимость регрессию в целом (F -статистика).

**$F$-статистика**

In [ ]:
F = R2*(len(x)-2)/(1-R2)
F

###### Result

In [218]:
# 2. Add a constant to the independent variable for the intercept
# This creates the design matrix for statsmodels
X_with_intercept = sm.add_constant(x)
# 3. Create and fit the OLS (Ordinary Least Squares) model
model = sm.OLS(y, X_with_intercept)
results = model.fit()
# 4. Print the detailed summary
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.967
Model:                            OLS   Adj. R-squared:                  0.955
Method:                 Least Squares   F-statistic:                     86.65
Date:                Wed, 25 Feb 2026   Prob (F-statistic):            0.00262
Time:                        12:41:08   Log-Likelihood:                -15.373
No. Observations:                   5   AIC:                             34.75
Df Residuals:                       3   BIC:                             33.96
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        -20.1000      7.090     -2.835      0.0

In [219]:
print(sigma_a, sigma_b)

7.090133990271267 2.137755832643195


In [220]:
t.ppf(0.025, len(x)-2)

np.float64(-3.1824463052842638)

## References

- [The Multiple Linear Regression Model](https://online.stat.psu.edu/stat462/node/131/)
- [Hypothesis Test for Linear Regression](https://stats.libretexts.org/Bookshelves/Introductory_Statistics/Mostly_Harmless_Statistics_(Webb)/12%3A_Correlation_and_Regression/12.02%3A_Simple_Linear_Regression/12.2.01%3A_Hypothesis_Test_for_Linear_Regression)
- [F-statistic: Understanding model significance using python](https://medium.com/analytics-vidhya/f-statistic-understanding-model-significance-using-python-c1371980b796)
- [F-test & F-statistics in Linear Regression: Formula, Examples](https://vitalflux.com/interpreting-f-statistics-in-linear-regression-formula-examples/)
- [Understand the F-statistic in Linear Regression](https://quantifyinghealth.com/f-statistic-in-linear-regression/)
- [P Value Calculator](https://www.graphpad.com/quickcalcs/pvalue1/)
- [F-distribution table](https://numiqo.com/tutorial/f-distribution)