In [1]:
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

## Cobb-Douglas production function

The **Cobb-Douglas production function** is a mathematical model used in economics to show the relationship between the quantity of a product and the inputs used to produce it, such as 
* **labor** and 
* **capital**. 

It is expressed as 

$$ Q = A K^{\alpha} L^{\beta},$$

where 
- $Q$ is output, 
- $K$ is capital, 
- $L$ is labor, 
- $A$ is total factor productivity, and 
- $\alpha$ and $\beta$ are the output elasticities for capital and labor, respectively. 

This function is widely used to estimate how changes in inputs affect output and to analyze technological change. 

In [9]:
# Q = np.array([1989, 6922, 11957, 44019, 14616, 3688, 46747, 9223, 3945, 4984, 14507, 4996, 1833, 7972, 37135, 39157])
# K = np.array([3806, 49716, 13687, 172228, 24742, 2971, 111, 9223, 3945, 4984, 14507, 4996, 1833, 7972, 37135, 39157])
# L = np.array([1989, 6922, 11957, 44019, 14616, 3688, 46747, 9223, 3945, 4984, 14507, 4996, 1833, 7972, 37135, 39157])

Q = np.array([1989, 6922, 11957, 44019, 14616, 3688, 46747, 9223 ])
K = np.array([3606, 49716, 13687, 172228, 24742, 2971, 111341, 34610])
L = np.array([7.6, 8, 27.4, 20.1, 20.1, 15.2, 22.1, 17.9])
I = np.array([1, 1, 1, 1, 1, 1, 1, 1])

In [5]:
np.log(K)

array([ 8.1903544 , 10.81408209,  9.52420176, 12.05657446, 10.11625748,
        7.99665388, 11.62035284, 10.45189794])

In [21]:
x = np.array([I, np.log(K), np.log(L)]) @ np.array([I, np.log(K), np.log(L)]).T
x

array([[  8.        ,  80.77037485,  22.12124618],
       [ 80.77037485, 830.65759289, 225.04784453],
       [ 22.12124618, 225.04784453,  62.71592099]])

In [20]:
np.linalg.inv(x)

array([[ 8.80355523, -0.53012272, -1.2029264 ],
       [-0.53012272,  0.07520683, -0.08288422],
       [-1.2029264 , -0.08288422,  0.73766191]])

In [16]:
print(np.linalg.inv(x),"\n", np.linalg.inv(x) @ x)

[[ 8.80355523 -0.53012272 -1.2029264 ]
 [-0.53012272  0.07520683 -0.08288422]
 [-1.2029264  -0.08288422  0.73766191]] 
 [[ 1.00000000e+00 -2.98699619e-13 -7.95652970e-14]
 [ 1.90421963e-15  1.00000000e+00  3.38216036e-15]
 [-7.67334624e-17  2.98650270e-14  1.00000000e+00]]


In [22]:
beta = np.linalg.inv(x) @ np.array([I, np.log(K), np.log(L)]) @ np.log(Q)
print( beta)

[0.91888887 0.5460661  1.02828269]
