In [1]:
import numpy as np
import pandas as pd

In [2]:
# from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [3]:
from IPython.display import display, Latex

In [4]:
import warnings
warnings.filterwarnings("ignore")

### Without intercept

In [ ]:
y = np.array([60, 36, 36, 15, 90])
x1 = np.array([40, 55, 45, 30, 30])
x2 = np.array([3, 6, 5, 3.5, 1.5])
p=2

In [ ]:
x = np.array([x1, x2]) @ np.array([x1, x2]).T
x

In [ ]:
beta = np.linalg.inv(x) @ np.array([x1, x2]) @ y
print( beta)

In [ ]:
e = y - beta @ np.array([x1, x2]) # unbiased estimate of error
sigma2 = sum([num ** 2 for num in e])/(len(y)-p)
sigma = np.sqrt(sigma2)

display(Latex(f"$\sum  e^2 = {sum([num ** 2 for num in e])}$"))
display(Latex(r"$\sigma^2 = \frac{1}{n-p}\sum e^2" + f" =  {sigma2}$"))
display(Latex(f"$\sigma = {sigma}$"))

In [ ]:
sigma_1 = np.sqrt( sigma2 * np.linalg.inv(x)[0, 0])
sigma_2 = np.sqrt( sigma2 * np.linalg.inv(x)[1, 1])
# sigma2 = 7.06

display(Latex(f"$\sigma^2_1 = " + r"\frac{\sigma^2}{\sum (x_1-\bar{x_1})^2}" + f" =  {sigma_1**2}$"))
display(Latex(f"$\sigma_1 =  {sigma_1}$"))
display(Latex(f"$\sigma^2_2 = " + r"\frac{\sigma^2}{\sum (x_2-\bar{x_2})^2}" + f" =  {sigma_2**2}$"))
display(Latex(f"$\sigma_2 =  {sigma_2}$"))

In [ ]:
# Convert to pandas DataFrame for easier handling, especially with the formula API
df = pd.DataFrame(np.array([x1, x2]).T, columns=['x1', 'x2'])
df['y'] = y

In [ ]:
# 3. Fit the OLS model
# Method 1: Using the direct OLS class
model_direct = sm.OLS(df['y'], df[['x1', 'x2']])
results_direct = model_direct.fit()

In [ ]:
# 4. Print the summary of the regression results
print("Results from direct OLS:")
print(results_direct.summary())

In [ ]:
print(sigma_1, sigma_2)
print(beta[0]/sigma_1, beta[1]/sigma_2)

### With intercept

In [ ]:
y = np.array([1, 2, 2, 3, 4])
I = np.array([1, 1, 1, 1, 1])
x1 = np.array([1, 2, 2, 1, 3])
x2 = np.array([10, 9, 9, 6, 6])
p=2

In [ ]:
x = np.array([I, x1, x2]) @ np.array([I, x1, x2]).T
x

In [ ]:
np.linalg.inv(x) @ np.array([I, x1, x2])

In [ ]:
np.array([I, x1, x2]) @ y

In [ ]:
beta = np.linalg.inv(x) @ np.array([I, x1, x2]) @ y
print( beta)

In [ ]:
e = y - beta @ np.array([I, x1, x2]) # unbiased estimate of error
sigma2 = sum([num ** 2 for num in e])/(len(y)-p-1)
sigma = np.sqrt(sigma2)

display(Latex(f"$\sum  e^2 = {sum([num ** 2 for num in e])}$"))
display(Latex(r"$\sigma^2 = \frac{1}{n-p-1}\sum e^2" + f" =  {sigma2}$"))
display(Latex(f"$\sigma = {sigma}$"))

In [ ]:
sigma_0 = np.sqrt( sigma2 * np.linalg.inv(x)[0, 0])
sigma_1 = np.sqrt( sigma2 * np.linalg.inv(x)[1, 1])
sigma_2 = np.sqrt( sigma2 * np.linalg.inv(x)[2, 2])
# sigma2 = 7.06

display(Latex(f"$\sigma^2_1 = " + r"\frac{\sigma^2}{\sum (x_1-\bar{x_1})^2}" + f" =  {sigma_1**2}$"))
display(Latex(f"$\sigma_1 =  {sigma_1}$"))
display(Latex(f"$\sigma^2_2 = " + r"\frac{\sigma^2}{\sum (x_2-\bar{x_2})^2}" + f" =  {sigma_2**2}$"))
display(Latex(f"$\sigma_2 =  {sigma_2}$"))

In [ ]:
# Convert to pandas DataFrame for easier handling, especially with the formula API
df = pd.DataFrame(np.array([x1, x2]).T, columns=['x1', 'x2'])
df['y'] = y

In [ ]:
# 2. Add a constant to the independent variables for the intercept term
# This is necessary when using the non-formula API (sm.OLS)
X_with_constant = sm.add_constant(df[['x1', 'x2']])

In [ ]:
# Method 2: Using the formula API (often more convenient)
# Requires 'statsmodels.formula.api'
model_formula = smf.ols("y ~ x1 + x2", data=df)
results_formula = model_formula.fit()

In [ ]:
# 4. Print the summary of the regression results
print("Results from formula OLS:")
print(results_formula.summary())

In [ ]:
print(sigma_0, sigma_1, sigma_2)
print(beta[0]/sigma_0, beta[1]/sigma_1, beta[2]/sigma_2)

### Control Work 2

#### Variants

In [33]:
# 1
y = np.array([1.3, 1.4, 0.7, 0.3, 0.1])
I = np.array([1, 1, 1, 1, 1])
x1 = np.array([3.8, 3.5, 4.1, 4.0, 3.8])
x2 = np.array([4.3, 4.4, 4.6, 4.8, 5.0])

In [98]:
# 2
y = np.array([2.4, 2.8, 3.2, 3.4, 3.2])
I = np.array([1, 1, 1, 1, 1])
x1 = np.array([5.3, 4.8, 4.3, 3.5, 3.2])
x2 = np.array([3.6, 4.1, 3.9, 3.6, 3.9])

In [45]:
# 3
y = np.array([2.5, 2.8, 3.0, 3.1, 3.0])
I = np.array([1, 1, 1, 1, 1])
x1 = np.array([4.8, 4.5, 4.1, 3.8, 3.5])
x2 = np.array([6.0, 5.8, 5.7, 5.6, 5.5])

In [77]:
# 4
y = np.array([2.8, 3.0, 3.2, 3.1, 3.0])
I = np.array([1, 1, 1, 1, 1])
x1 = np.array([3.5, 3.2, 3.0, 2.8, 2.7])
x2 = np.array([6.5, 6.4, 6.3, 6.2, 6.1])

In [ ]:
# 5
y = np.array([1.5, 1.8, 2.0, 2.1, 1.9])
I = np.array([1, 1, 1, 1, 1])
x1 = np.array([3.8, 3.5, 3.2, 3.0, 2.8])
x2 = np.array([2.9, 2.8, 2.7, 2.8, 2.9])

In [6]:
# 6
y = np.array([-2.5, -2.0, -1.5, -0.8, 0.1])
I = np.array([1, 1, 1, 1, 1])
x1 = np.array([5.0, 4.8, 4.5, 4.0, 3.5])
x2 = np.array([7.2, 7.5, 7.8, 8.0, 8.1])

In [5]:
# 7
y = np.array([-0.5, -0.3, 0.1, 0.5, 0.7])
I = np.array([1, 1, 1, 1, 1])
x1 = np.array([3.5, 3.2, 3.0, 2.8, 2.5])
x2 = np.array([7.2, 7.4, 7.5, 7.4, 7.3])

In [55]:
# 8
y = np.array([2.5, 2.8, 3.0, 3.1, 3.0])
I = np.array([1, 1, 1, 1, 1])
x1 = np.array([3.2, 2.8, 2.5, 2.2, 2.0])
x2 = np.array([10.5, 10.3, 10.1, 9.9, 9.7])

In [22]:
# 9
y = np.array([2.5, 2.8, 3.0, 3.1, 3.0])
I = np.array([1, 1, 1, 1, 1])
x1 = np.array([3.5, 3.2, 3.0, 2.8, 2.5])
x2 = np.array([11.8, 11.5, 11.3, 11.1, 10.9])

In [89]:
# 10
y = np.array([0.8, 1.0, 1.2, 1.1, 1.0])
I = np.array([1, 1, 1, 1, 1])
x1 = np.array([3.5, 3.2, 3.0, 2.8, 2.5])
x2 = np.array([3.6, 3.5, 3.4, 3.4, 3.5])

In [65]:
# 11
y = np.array([-0.5, -0.1, 0.4, 0.8, 1.0])
I = np.array([1, 1, 1, 1, 1])
x1 = np.array([4.8, 4.5, 4.1, 3.8, 3.5])
x2 = np.array([6.8, 7.0, 6.9, 6.8, 6.7])

#### Solution

In [6]:
p=2

In [7]:
x = np.array([I, x1, x2]) @ np.array([I, x1, x2]).T
x

array([[  5.  ,  15.  ,  36.8 ],
       [ 15.  ,  45.58, 110.35],
       [ 36.8 , 110.35, 270.9 ]])

In [8]:
np.linalg.inv(x) @ np.array([I, x1, x2])

array([[ 16.28850325,  -9.97903109, -22.16558207,  -2.40130152,
         19.25741142],
       [  0.65075922,   0.4483008 ,   0.25307303,  -0.30368764,
         -1.04844541],
       [ -2.45119306,   1.20028923,   2.93564714,   0.47722343,
         -2.16196674]])

In [9]:
np.array([I, x1, x2]) @ y

array([0.5 , 0.74, 3.74])

In [10]:
beta = np.linalg.inv(x) @ np.array([I, x1, x2]) @ y
print( beta)

[ 4.91243673 -1.32031815 -0.11569053]


In [11]:
e = y - beta @ np.array([I, x1, x2]) # unbiased estimate of error
sigma2 = sum([num ** 2 for num in e])/(len(y)-p-1)
sigma = np.sqrt(sigma2)

display(Latex(f"$\sum  e^2 = {sum([num ** 2 for num in e])}$"))
display(Latex(r"$\sigma^2 = \frac{1}{n-p-1}\sum e^2" + f" =  {sigma2}$"))
display(Latex(f"$\sigma = {sigma}$"))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [12]:
sigma_0 = np.sqrt( sigma2 * np.linalg.inv(x)[0, 0])
sigma_1 = np.sqrt( sigma2 * np.linalg.inv(x)[1, 1])
sigma_2 = np.sqrt( sigma2 * np.linalg.inv(x)[2, 2])
# sigma2 = 7.06

display(Latex(f"$\sigma^2_1 = " + r"\frac{\sigma^2}{\sum (x_1-\bar{x_1})^2}" + f" =  {sigma_1**2}$"))
display(Latex(f"$\sigma_1 =  {sigma_1}$"))
display(Latex(f"$\sigma^2_2 = " + r"\frac{\sigma^2}{\sum (x_2-\bar{x_2})^2}" + f" =  {sigma_2**2}$"))
display(Latex(f"$\sigma_2 =  {sigma_2}$"))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [13]:
# Convert to pandas DataFrame for easier handling, especially with the formula API
df = pd.DataFrame(np.array([x1, x2]).T, columns=['x1', 'x2'])
df['y'] = y

In [14]:
# 2. Add a constant to the independent variables for the intercept term
# This is necessary when using the non-formula API (sm.OLS)
X_with_constant = sm.add_constant(df[['x1', 'x2']])

In [15]:
# Method 2: Using the formula API (often more convenient)
# Requires 'statsmodels.formula.api'
model_formula = smf.ols("y ~ x1 + x2", data=df)
results_formula = model_formula.fit()

In [16]:
# 4. Print the summary of the regression results
print("Results from formula OLS:")
print(results_formula.summary())

Results from formula OLS:
                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.958
Model:                            OLS   Adj. R-squared:                  0.916
Method:                 Least Squares   F-statistic:                     22.91
Date:                Fri, 12 Dec 2025   Prob (F-statistic):             0.0418
Time:                        11:09:46   Log-Likelihood:                 4.7664
No. Observations:                   5   AIC:                            -3.533
Df Residuals:                       2   BIC:                            -4.705
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      4.9124     

In [17]:
print(sigma_0, sigma_1, sigma_2)
print(beta[0]/sigma_0, beta[1]/sigma_1, beta[2]/sigma_2)

5.178193684734801 0.20221036347588953 0.6753295212233632
0.9486776723357246 -6.529428691269397 -0.1713097446530065
